### PR TITLE
tikz and asymptote files

### PR DESCRIPTION
**Pull request by davidfarmer**
First attempt at reading in the tikz and asymptote figure files.

15 files were not found.

I haven't checked things carefully yet, but wanted to let you see the progress and
make a reality check.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
For some images, this worked. This created 55 `<latex-image-code>` elements, and they all went smoothly through the mbx script to make svgs, although I did not examine each one.

But only 55. Most of the images are still only included using source="foo.png", even though some tex source for the image does exist in the original repo.

For example, `fig_derivfalling.tex` is in the original repo. But in `sec_derivatives.mbx`, SL2X produced `<image width="73%" source="images/figderivfalling.png" />` instead of the `<latex-image-code>` (and its wrappers).

**Comment by davidfarmer** [comment]
Something is wrong, because I see the tikz source of that image
in the mbx files on my system.  Maybe I sent the wrong pull request or 
something.

I'll send another pull request and check it more carefully.

**Comment by davidfarmer** [comment]
It looks like the problem is old files which should be deleted.
There is no sec_derivatives.mbx file, but there is
sec_derivative.mbx, and it has the correct image markup.

In the next pull request there will be an mbx2 directory that
contains only the newest files.

Maybe I need to use git differently when all I am doing is
generating files from a script.

**Comment by Alex-Jordan** [comment]
My fault. Looks like I hadn't pulled. I get 55 hits from commit d92c8bec78e208e60c9bd2ee27dbbd6d0309f080, which was before this.

My plan is to purge the repo of all memory of the mbx folder (and now also mbx2) and put the final .mbx files into the src folder once we are done with automated conversion. Sound OK?

**Comment by davidfarmer** [comment]
Yes, we need to deal with the mbx files as a unit and just move them 
around until we get to the hand-editing stage.

**Pull request merged**
