### PR TITLE
images and notation issues

### PR DESCRIPTION
**Pull request by CVollet**

### CODE REVIEW

**Comment by davidfarmer** [comment]
If the punctuation should be after the "md" instead of after the last "mrow", then I can
run a script to change all of them.  It was not clear to me that it had been decided.

**Comment by CVollet** [comment]
As far as I can tell, if you put a punctuation after an mrow, it doesn't do
anything (i.e. the punctuation doesn't show). Maybe I forgot exactly what
we decided?

**Comment by CVollet** [comment]
The last email I have from Rob was "option 3", which was
<mrow>
<md>.

**Comment by Alex-Jordan** [comment]
Just hit this issue in APEX. Is there a reason that `\label` is actually used in MathJax? Could we just redefine `\label` to do nothing in the MathJax header?

**Pull request merged**
