### PR TITLE
changed spacing around p, cell, caption, title, and image

### PR DESCRIPTION
**Pull request by davidfarmer**
Partial progress on items 2, 3, 4, and 7 of your list.

I don't think you meant to say that _everything_ in a paragraph should be on one line.
For now, all I did was make inline the opening and closing tags.
(Which I happen to think is bad practice, but I understand that some technical
limitations may require that for now.  It is easy to fix it later.)

Not sure how you are supposed to evaluate a pull request with so many changes.

The changes were made with this script:
https://github.com/davidfarmer/LaTeXtoLaTeX
by making a "src2" directory, putting the converted files there, and then copying them
back to "src".

### CODE REVIEW

**Comment by davidfarmer** [comment]
New commit for item 8: replace exercises with webwork skeleton.

**Comment by davidfarmer** [comment]
I also addressed item 6 (xml:id on image in figure).  There were 22 case where a figure
with an xml:id contained more than one image, so I didn't do anything in those cases.
Should I do something like put a counter on the ids?

**Comment by Alex-Jordan** [comment]
> Not sure how you are supposed to evaluate a pull request with so many changes.

I'll try pulling it to a testing branch and doing a few things from there.

> I don't think you meant to say that everything in a paragraph should be on one line.

Yes, I overlooked ul, ol, dl, md, mdn, cd, maybe more. 

>  Should I do something like put a counter on the ids?

If there are only 22 instances, I can handle them individually. They will stand out when images are processed because the image files will not have perma-names.

It probably will not be today that I can review all this, but thanks for the lightning fast progress.

**Comment by Alex-Jordan** [comment]
I just approved #27, which now makes this one have conflicts. If you have a good way  to address that, fine. But since #27 is localized to the intro limits section, It'll be fine for me to manually address the conflict when I'm ready.

**Comment by davidfarmer** [comment]
I will send a new pull request shortly.

**Comment by Alex-Jordan** [comment]
Closing because of new merge conflict, replacing with #29.

**Pull request closed without merging**
