### PR TITLE
Graphs readability

### PR DESCRIPTION
**Pull request by CVollet**

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
You removed the white texted tan(theta) from the latter triangle graphs. If you do that the three triangles will be stretched out to different sizes and harder to compare side by side in the HTML. These "invisible" labels are there so that the bounding box on all three triangles is exactly the same. 

Making them white was maybe not the best way to do it. Perhaps you can set opacity=0 and that would work. Would you mind testing? Be sure to make images before you make html. As it is with the tan(theta)'s removed, I'm sure the triangles are going to look messed up next to each other.

**Comment by Alex-Jordan** [comment]
You put `<-` and `->` directly into some image code. This makes it hard for Greg to remove those arrows, and he expressed a preference to only have arrows in straight-line graphs.

For this reason, the preamble has `leftarrow` and `rightarrow` styles. These can be made to do nothing when the time comes to make say Greg's version.

There are times when it is correct to use `<-`, `<->`, and `->`. Use those styles when what you are making is a straight line. Where no one disagrees about having arrows. And resetting `leftarrow` and `rightarrow` won't change the behavior.

In the one rational function plot, why split it up into two parts? Unless one of the samples happens to ends up at x=3.00000, it should work out OK. You could also have tikz plot the reduced rational function instead.

**Comment by Alex-Jordan** [comment]
`\addplot+[domain=0:6,firstcurvestyle...`

suggests maybe you are not familiar with `\addplot` versus `\addplot+`.

When you use `\addplot+`, it cycles through `firstcurvestyle`, `secondcurvestyle`, `thirdcurvestyle`, and back. You are supposed to be liberated from thinking about the styling. You use:

```
\addplot+[]{x};
\addplot+[]{x^2};
```

And they will be styled differently. If you explicitly want them styled the same, then:

```
\addplot[firstcurvestyle]{x};
\addplot[firstcurvestyle]{x^2};
```

with no +.

**Comment by Alex-Jordan** [comment]
`\addplot[soliddot, firstcurvestyle] coordinates {(1,10) (5,20)};`

does not only make solid dots. Because `firstcurvestyle` is last, it tacks on all the options there, and you will end up with a line plotted between the points. In this case there is a linear function there anyway, so you may not notice. But it's still important to understand.

**Comment by CVollet** [comment]
I think I addressed all of the issues.

**Pull request merged**
