### PR TITLE
Titles to WW exercises in sec_limit_analytically

### PR DESCRIPTION
**Pull request by davidfarmer**
I added short titles to the WW exercises in sec_limit_analytically,
and also wrapped a up in a p (which may or may not address part
of an issue I just submitted).

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
OK, thanks for the initiative here. I should probably be doing these though, because sometimes I'll be coding randomization into the problem that will be at odds with a specific title. I get the simplicity of how titles can be though, and I'll follow your lead.

**Comment by davidfarmer** [comment]
I am just proposing very short titles as an option.  Best practices
will emerge as we get used to doing new things.  I am still trying to
grasp the idea of having so many WW problems.  I had assumed most
of the book would look like the PDF, with a few WW here and there.

**Comment by Alex-Jordan** [comment]
Looks like there will be no conflicts between this and the webwork editing I'm in the middle of. Planning to finish that, update #47 if that is still open (or make a new PR if necessary) then merge this one.

**Comment by CVollet** [comment]
I'm not comfortable enough with github to deal with the conflicts in this pull request.

**Comment by Alex-Jordan** [comment]
I'm still finishing WeBWorK conversions for this section. As I mentioned above, not planning to merge this until I'm done. So I'm glad you didn't try ;)

**Comment by Alex-Jordan** [comment]
Locally addressed conflicts and pushed. This commit is on master now. And the result is visible at http://spot.pcc.edu/math/APEXCalculus/sec_limit_analytically.html.

**Pull request merged**
