### PR TITLE
Finished manual reorganizing of limits intro figures and tables

### PR DESCRIPTION
**Pull request by Alex-Jordan**

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
Carly, have you had a chance to review this? I recommend clicking the "Files changed" tab and browsing through the changes. This one now has all of the WeBWorK stuff at the end so you can skip over that. I'd be scanning where some sort of replacement was made, like "Figure" to "Table" and checking that it was appropriate.

**Comment by CVollet** [comment]
There are too many changes for me to view on Git Hub. I don't know how to view the changes locally using git diff. I'm going to go ahead and approve it, but maybe you can help me for things like this in the future. For some reason I'm not getting notifications of your pull requests.

**Comment by Alex-Jordan** [comment]
@CVollet Try visiting this repo on GitHub (the PCCMathSAC one, not the CVollet one) and clicking the star on the top right. I'm thinking that once you do that you will get an alert about anything anywhere on the repo. I've never actually starred anything, but since the two of us are fully in charge of this project, now would be the time. I just starred it myself.

**Comment by davidfarmer** [comment]
I'm pretty sure you want to "watch", not "star".

**Pull request merged**
