### PR TITLE
re-build after merging

### PR DESCRIPTION
**Pull request by davidfarmer**
Use this pull request instead.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
OK, just got around to pulling this onto a test branch and trying it. Looks like a lot of broken syntax. I got so many issues scrolling past I'm not sure I could catalog them all, so maybe we can try to trim them down a few at a time.

It looks like in many places where you should have closing `figure` tags, now there are open `figure` tags.

In some places, there is stuff like this:
`<figure xml:id= xml:id="fig_trip7" >`

I get a lot of open/close tag mismatches, but they could be consequences of these first two things. Did you configure `Makefile.paths` so that you can run `make check`? Or otherwise run `xmllint` on the output, and you can see all (many of?) the errors.

**Comment by davidfarmer** [comment]
Looks like I forgot to re-run xmllint after my last round
of changes.  Looking at it now.

**Comment by davidfarmer** [comment]
I fixed at least some of those problems.

Running against the DTD shows a lot more errors, which I think are
due to the new WeBWorK framework

Let's just try to fix one thing at a time.  Let me know the next
problem you find.

If you prefer, I can re-make this as a completely fresh pull request.

**Comment by Alex-Jordan** [comment]
OK, I just checked this out locally and set the image-making to run. Should be done when I come back later and I can count that we still have the same number of images. Then I'll make the html and look around to see if I notice anything amiss. 

I notice now that we have no provision for a simple "answer" in a "webwork", as opposed to a "solution", and the DTD is objecting to an this. I'll post in the main MBX forum about this because it leads to an MBX design question.

**Comment by Alex-Jordan** [comment]
Can you only apply these new edits to files other than `sec_limit_intro.mbx`? Certain things appear to have gotten messed with. In particular what I notice is the webwork exercises have lost a lot of their structure and been turned into the simple templates.

**Comment by davidfarmer** [comment]
I put back the original sec_limit_intro.mbx

**Comment by Alex-Jordan** [comment]
Working well, except for some bugs with unescaped `<` that I missed the last time I made a commit.

**Pull request merged**
